name: Keep-Alive Streamlit

# 定期実行の設定
# このワークフローは毎時実行され、また手動でも実行可能です。
on:
  schedule:
    - cron: "*/60 * * * *"  # 毎時60分ごとに実行
  workflow_dispatch:        # 手動実行も可能にする

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Send a full request to simulate user session and keep the app awake
        run: |
          echo "Fetching full page to simulate a user session and keep the app awake..."
          curl -L -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36" https://concur-dev-support.streamlit.app/ || true
