name: Keep Streamlit App Alive

on:
  schedule:
    # 1時間ごとに実行 (UTC時間)
    - cron: '0 */1 * * *'
  workflow_dispatch:  # 手動実行用

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager requests
      
      - name: Run keep-alive script
        run: python keep_alive.py
        env:
          STREAMLIT_EMAIL: ${{ secrets.STREAMLIT_EMAIL }}
          STREAMLIT_EMAIL_PASSWORD: ${{ secrets.STREAMLIT_EMAIL_PASSWORD }}
          EMAIL_IMAP_SERVER: mas22.kagoya.net
          EMAIL_USERNAME: libertas.kishiyaman
      
      - name: Upload screenshots as artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots
          path: screenshot_*.png
          retention-days: 5